exam/bulletin/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', BoardsListView.as_view(), name='board-home'),
    path('<int:pk>/', BoardsDetailView.as_view(), name='board-details'),
    path('board/new/', BoardsCreateView.as_view(), name='board-create'),
    path('board/<int:pk>/delete/', BoardsDeleteView.as_view(), name='board-delete'),
    path('thread/<int:pk>/', ThreadsDetailView.as_view(), name='thread-details'),
    path('post/<int:pk>/new/', PostCreateView.as_view(), name='post-create'),
    path('thread/<int:pk>/new/', ThreadCreateView.as_view(), name='thread-create'),
    path('thread/<int:pk>/lock/', ThreadUpdateView.as_view(), name='thread-update'),
]

exam/exam/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name="register"),
    path('profile/', user_views.profile, name="profile"),
    path('ban/<int:pk>/', user_views.ProfileUpdateView.as_view(), name="user-ban"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('bulletin.urls')),
]

exam/bulletin/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Boards(models.Model):
    name = models.CharField(max_length=30)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    created_on = models.DateField(auto_now=True)
    position_in_home = models.PositiveIntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('board-details', kwargs={'pk': self.pk})

class Threads(models.Model):
    title = models.CharField(max_length=50)
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    posted_on = models.DateField(auto_now=True)
    is_locked = models.BooleanField()
    boards = models.ForeignKey(Boards, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board-home')


class Post(models.Model):
    message = models.CharField(max_length=100)
    posted_on = models.DateField(auto_now=True)
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    threads = models.ForeignKey(Threads, on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def get_absolute_url(self):
        return reverse('board-home')

exam/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.urls import reverse

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    banned = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('board-home')

def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

post_save.connect(create_profile, sender=User)

exam/users/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm

class UserForm(UserCreationForm):
    email = forms.EmailField()
    group = forms.ModelChoiceField(queryset=Group.objects.all(), required=True)
    class Meta:
        model = User
        fields = ['username', 'group', 'email', 'password1', 'password2']

    #def __init__(self, *args, **kw):
    #    super(UserForm, self).__init__(*args, **kw)
    #    self.fields['group'].queryset=Group.objects.filter(user=self.instance.id)

exam/bulletin/views.py
from django.views import generic
from .models import *
from django.shortcuts import get_object_or_404

class BoardsListView(generic.ListView):
    model = Boards
    template_name = 'bulletin/home.html'
    context_object_name = 'board_list'
    ordering = ['position_in_home']

class BoardsCreateView(generic.CreateView):
    model = Boards
    fields = ['name', 'position_in_home']

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super(BoardsCreateView, self).form_valid(form)

class BoardsDeleteView(generic.DeleteView):
    model = Boards
    success_url = '/'

class BoardsDetailView(generic.DetailView):
    model = Boards
    template_name = 'bulletin/boards_details.html'

class ThreadsDetailView(generic.DetailView):
    model = Threads
    template_name = 'bulletin/thread_details.html'
    context_object_name = 'thread_list'

class ThreadCreateView(generic.CreateView):
    model = Threads
    fields = ['title', 'is_locked']

    def form_valid(self, form):
        form.instance.posted_by = self.request.user
        form.instance.boards = Boards.objects.get(pk=self.kwargs.get('pk'))
        return super(ThreadCreateView, self).form_valid(form)

class ThreadUpdateView(generic.UpdateView):
    model = Threads
    fields = ['is_locked']
    def form_valid(self, form):
        form.instance.posted_by = self.request.user
        #form.instance.boards = Boards.objects.get(pk=self.kwargs.get('pk'))
        return super(ThreadUpdateView, self).form_valid(form)

class PostCreateView(generic.CreateView):
    model = Post
    fields = ['message']

    def form_valid(self, form):
        form.instance.posted_by = self.request.user
        form.instance.threads = Threads.objects.get(pk=self.kwargs.get('pk'))
        return super(PostCreateView, self).form_valid(form)


class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'bulletin/home.html'
    context_object_name = "post_list"

exam/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserForm
from django.contrib.auth.decorators import login_required
from django.views import generic
from .models import *
from django.contrib.auth.models import Group, User

def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            User = form.save()
            #group = Group.objects.get(form.cleaned_data['group'])
            User.groups.add(form.cleaned_data['group'] )
            messages.success(request, 'Account created!')
            return redirect('login')
    else:
        form = UserForm()
    return render(request, 'users/register.html', {'form': form})

@login_required
def profile(request):
    return render(request, 'users/profile.html')



class ProfileUpdateView(generic.UpdateView):
    model = Profile
    fields = ['banned']

exam/bulletin/templates/bulletin/base.html
{% load static %}
{% load user_group_tags %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> Bulletin Board </title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'bulletin/main.css' %}">
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'board-home' %}">Home</a>
            </div>
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                  {% if user|has_group:"administrator" %}
                    <a class="nav-item nav-link"> Administrator </a>
                  {% endif %}
                  {% if user|has_group:"moderator" %}
                    <a class="nav-item nav-link"> Moderator </a>
                  {% endif %}
                  {% if user|has_group:"poster" %}
                    <a class="nav-item nav-link"> Poster </a>
                  {% endif %}
                <a class="nav-item nav-link" href="{% url 'logout' %}"> Logout </a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'register' %}"> Register </a>
                <a class="nav-item nav-link" href="{% url 'login' %}"> Login </a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
          <div class="col-md-8">
            {% if messages %}
                {% for message in messages %}
                    {{ message}}
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock %}
        </div>
      </div>
    </main>
</body>
</html>

exam/bulletin/templates/bulletin/boards_confirm_delete.html
{% extends "bulletin/base.html" %}
{% block content %}

    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h4>Are you sure you want to delete the post "{{ object.name }}" ?</h4>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'board-details' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

exam/bulletin/templates/bulletin/boards_details.html
{% extends "bulletin/base.html" %}
{% load user_group_tags %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <h2 class="article-title">{{ object.name }}</h2>
            <p class="article-content">posted by: {{ object.creator }}</p>

                {% for threads in object.threads_set.all reversed %}
                    <a href="{% url 'thread-details' threads.id %}"><h5>{{ threads.title }}</h5></a>
                    {% if threads.is_locked %}
                        <small> This thread is locked </small>
                        {% if user|has_group:"moderator" or user|has_group:"administrator" %}
                            <a href="{% url 'thread-update' threads.id %}"> (unlock) </a>
                        {% endif %}
                    {% else %}
                        <small> This thread is not locked </small>
                        {% if user|has_group:"moderator" or user|has_group:"administrator" %}
                            <a href="{% url 'thread-update' threads.id %}"> (lock this thread) </a>
                        {% endif %}
                    {% endif %}

                    {% for post in threads.post_set.all %}
                        {% if forloop.last %}
                            <p> {{ post.posted_on }} - {{ post.posted_by }} </p>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            <br>
            {% if user|has_group:"administrator" %}
                <a href="{% url 'thread-create' object.id %}"><button type="submit"> Add Threads </button></a>
                <a href="{% url 'board-delete' object.id %}"><button type="submit"> Delete this Board </button></a>
            {% endif %}
        </div>
    </article>
{% endblock content %}

exam/bulletin/templates/bulletin/boards_form.html
{% extends "bulletin/base.html" %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Okay">
    </form>
{% endblock content %}

exam/bulletin/templates/bulletin/home.html
{% extends "bulletin/base.html" %}
{% load user_group_tags %}
{% block content %}
    {% for board in board_list %}
        <article class="media content-section">
            <div class="media-body">
                <a href="{% url 'board-details' board.id %}"><h3> {{ board.name }} </h3></a>
                <small class="text-muted"> number of threads: {{ board.threads_set.all|length }} </small><br>
                {% for threads in board.threads_set.all %}
                    {% if forloop.last %}
                        {% for post in threads.post_set.all %}
                            {% if forloop.last %}
                                <small class="text-muted"> most_recent_reply: 
                                    <a href="{% url 'thread-details' threads.id %}">{{ threads.title }} </a>
                                </small> <br>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endfor %}

                <small class="text-muted"> number of post: {{ board.threads_set.last.post_set.all|length }} </small>
            </div>
        </article>
    {% endfor %}

                {% if user|has_group:"administrator" %}
                    <a href="{% url 'board-create' %}"><button type="submit"> Add New Board </button></a>
                {% endif %}
{% endblock content %}

exam/bulletin/templates/bulletin/post_form.html
{% extends "bulletin/base.html" %}
{% block content %}

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="POST">
    </form>
{% endblock content %}

exam/bulletin/templates/bulletin/thread_details.html
{% extends "bulletin/base.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <h6 class="article-title"> {{ object.boards }} </h6>
            <h2 class="article-title">{{ object.title }}</h2>
            <p class="article-content">posted by: {{ object.posted_by }}</p>

                {% for post in object.post_set.all %}
                     <a href="{% url 'user-ban' post.posted_by.profile.id %}">{{ post.posted_by }}</a>  <p> {{ post.posted_on }} - {{ post.message }} </p>
                {% endfor %}
                {% if object.is_locked %}
                    <a href="{% url 'thread-update' object.id %}"> Unlock this Thread </a>
                {% else %}
                    {% if user.profile.banned %}
                        <small> You are banned! </small>
                    {% else %}
                        <a href="{% url 'post-create' object.id %}"> Reply </a>
                    {% endif %}
                {% endif %}

        </div>
    </article>

{% endblock content %}

exam/bulletin/templates/bulletin/threads_form.html
{% extends "bulletin/base.html" %}
{% block content %}

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="POST">
    </form>
{% endblock content %}

exam/users/templates/users/login.html
{% extends "bulletin/base.html" %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Login </button>
    </form>

    <a href="{% url 'register' %}"> Sign Up</a>
{% endblock content %}

exam/users/templates/users/logout.html
{% extends "bulletin/base.html" %}
{% block content %}
    <h3> Logout Successful! </h3>
    <a href="{% url 'login' %}"> Login Again? </a>
{% endblock content %}

exam/users/templates/users/profile.html
{% extends "bulletin/base.html" %}
{% load user_group_tags %}
{% block content %}
    <h1> {{ user.username }} </h1>
    <h1> {{ user.email }} </h1>
    <h1> {{ user.profile.banned }} </h1>

    {% if user|has_group:"administrator" %}
        <p>administrator</p>
    {% endif %}

    {% if user|has_group:"moderator" %}
        <p>moderator</p>
    {% endif %}

    {% if user|has_group:"poster" %}
        <p>poster</p>
    {% endif %}

{% endblock content %}

exam/users/templates/users/profile_form.html
{% extends "bulletin/base.html" %}
{% load user_group_tags %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <h4> {{ object.user.username }} </h4>
        <hr>
        <h6> {{ object.user.email }} </h6>
        <hr>
        {% if user|has_group:"moderator" or user|has_group:"administrator" %}
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit"> Submit </button>
                </div>
            </form>
        {% else %}
            <h4> You don't have ability to ban Users. </h4>
        {% endif %}
    </div>
{% endblock content %}

exam/users/templates/users/register.html
{% extends "bulletin/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}